# Generated by Django 3.1 on 2020-10-23 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_info', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basicinfo',
            old_name='asfn',
            new_name='afsn',
        ),
    ]
