# Generated by Django 3.1.3 on 2020-11-21 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_info', '0002_auto_20201023_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicinfo',
            name='afsn',
            field=models.CharField(blank=True, max_length=10, verbose_name='AFSN'),
        ),
        migrations.AlterField(
            model_name='basicinfo',
            name='assign',
            field=models.CharField(blank=True, max_length=20, verbose_name='CURRENT UNIT'),
        ),
        migrations.AlterField(
            model_name='basicinfo',
            name='category',
            field=models.CharField(blank=True, max_length=20, verbose_name='CATEGORY'),
        ),
        migrations.AlterField(
            model_name='basicinfo',
            name='firstname',
            field=models.CharField(blank=True, max_length=50, verbose_name='FIRST NAME'),
        ),
        migrations.AlterField(
            model_name='basicinfo',
            name='lastname',
            field=models.CharField(blank=True, max_length=50, verbose_name='LASTNAME'),
        ),
        migrations.AlterField(
            model_name='basicinfo',
            name='middlename',
            field=models.CharField(blank=True, max_length=50, verbose_name='MIDDLE NAME'),
        ),
        migrations.AlterField(
            model_name='basicinfo',
            name='rank',
            field=models.CharField(blank=True, max_length=20, verbose_name='RANK'),
        ),
    ]
