# Generated by Django 3.1.6 on 2021-02-12 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_info', '0003_auto_20201121_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicinfo',
            name='sex',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=20),
        ),
    ]
