# Generated by Django 3.1.6 on 2021-02-12 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_info', '0004_basicinfo_sex'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basicinfo',
            name='category',
        ),
        migrations.RemoveField(
            model_name='basicinfo',
            name='sex',
        ),
        migrations.AddField(
            model_name='basicinfo',
            name='classification',
            field=models.CharField(blank=True, max_length=20, verbose_name='CLASSIFICATION'),
        ),
        migrations.AddField(
            model_name='basicinfo',
            name='extensionname',
            field=models.CharField(blank=True, max_length=50, verbose_name='EXTENSION NAME'),
        ),
        migrations.AddField(
            model_name='basicinfo',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=20, verbose_name='GENDER'),
        ),
        migrations.AddField(
            model_name='basicinfo',
            name='source',
            field=models.CharField(blank=True, max_length=20, verbose_name='SOURCE OF COMMISION'),
        ),
        migrations.AlterField(
            model_name='basicinfo',
            name='lastname',
            field=models.CharField(blank=True, max_length=50, verbose_name='LAST NAME'),
        ),
    ]
