# Generated by Django 3.1.6 on 2021-02-12 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_info', '0006_basicinfo_startdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basicinfo',
            old_name='startdate',
            new_name='dateenlist',
        ),
    ]
