# Generated by Django 3.1.6 on 2021-02-12 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_info', '0007_auto_20210212_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicinfo',
            name='datecompret',
            field=models.DateField(blank=True, null=True),
        ),
    ]
