# Generated by Django 3.1.6 on 2021-02-12 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_info', '0008_basicinfo_datecompret'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basicinfo',
            old_name='dateenlist',
            new_name='dateentersvc',
        ),
        migrations.AlterField(
            model_name='basicinfo',
            name='classification',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=20, verbose_name='CLASSIFICATION'),
        ),
    ]
