# Generated by Django 3.1.3 on 2021-02-16 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_info', '0009_auto_20210212_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicinfo',
            name='classification',
            field=models.CharField(blank=True, choices=[('Officer', 'Officer'), ('Enlisted', 'Enlisted')], max_length=20, verbose_name='CLASSIFICATION'),
        ),
        migrations.AlterField(
            model_name='basicinfo',
            name='datecompret',
            field=models.DateField(blank=True, null=True, verbose_name='DATE OF COMPULSORY RETIREMENT'),
        ),
        migrations.AlterField(
            model_name='basicinfo',
            name='dateentersvc',
            field=models.DateField(blank=True, null=True, verbose_name='DATE ENTERED SERVICE'),
        ),
    ]
