# Generated by Django 3.1.3 on 2021-02-16 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(max_length=100)),
                ('unitname', models.CharField(max_length=100)),
                ('unitdescription', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='assignment',
            name='category',
            field=models.CharField(blank=True, choices=[('Primary', 'Primary Duty'), ('Additional', 'Additional Duty')], max_length=20),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignment.unitlist'),
        ),
    ]
