# Generated by Django 3.1.3 on 2020-11-11 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='enddate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='training',
            name='startdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
