# Generated by Django 3.1.3 on 2020-11-13 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0007_auto_20201113_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='training.course'),
        ),
    ]
