# Generated by Django 3.1.3 on 2020-11-14 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0012_auto_20201114_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.course'),
        ),
    ]
