# Generated by Django 3.1.3 on 2020-11-14 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0013_auto_20201114_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='completed',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('Female', 'Female')], max_length=20),
        ),
    ]
