# Generated by Django 3.1.3 on 2020-11-14 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0014_auto_20201114_1010'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schoolname', models.CharField(max_length=50)),
                ('schoolfullname', models.CharField(max_length=50)),
                ('schooladdress', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='training',
            name='completed',
            field=models.CharField(blank=True, choices=[('True', 'True'), ('False', 'False')], max_length=20),
        ),
    ]
