# Generated by Django 3.1.3 on 2020-11-14 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0015_auto_20201114_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='coursedescription',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='course',
            name='coursename',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='school',
            name='schoolfullname',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='school',
            name='schoolname',
            field=models.CharField(max_length=100),
        ),
    ]
