# Generated by Django 3.1.3 on 2020-11-14 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0016_auto_20201114_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.school'),
        ),
    ]
