# Generated by Django 3.1.3 on 2020-11-14 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0017_auto_20201114_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='school',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
