# Generated by Django 3.1.3 on 2020-11-14 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0018_auto_20201115_0000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='training',
            name='school',
        ),
    ]
