# Generated by Django 3.1.3 on 2020-11-14 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0019_remove_training_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='training.school'),
            preserve_default=False,
        ),
    ]
